global:
  interval: 10s
  repeat: 15m
  workers: 30
web:
  - name: Main Page
    url: https://google.com
    expectedCode: 200
    # naame url ExpCode RcvCode
    msg: "<b>WARNING</b>\n<code>Host:</code>    <a href='{{.URL}}'>{{.Name}}</a>\n<code>Expected Code:</code>    <em>{{.ExpCode}}</em>\n<code>Got:</code>    <em>{{.RcvCode}}</em>\n"
    headers:
      - key: Auth
        value: "abc"
    

tlg:
  token: TOKEN
  chats:
    - 93999207  #George K
        