global:
  interval: 10s
  repeat: 15m
  workers: 30
web:
  main_page:
    url: https://google.com
    expectedCode: 200
    labels:
      name: My Main Page
      url: https://google.com
      code: 200
    msg: "<b>WARNING</b>\n<code>Host:</code>    <a href='{{ $labels.url }}'>{{ $labels.name }}</a>\n<code>Expected Code:</code>    <em>{{ $labels.code}}</em>\n<code>Got:</code>    <em>{{ $value.code }}</em>\n"
    headers:
      - key: Auth
        value: "abc"
  app_page:
    url:    

tlg:
  token: TOKEN
  chats:
    - 93999207  #George K
